-- MySQL Script generated by MySQL Workbench
-- Tue May 21 22:27:07 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema p9_uoc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema p9_uoc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `p9_uoc` DEFAULT CHARACTER SET utf8 ;
USE `p9_uoc` ;

-- -----------------------------------------------------
-- Table `p9_uoc`.`Roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `p9_uoc`.`Roles` (
  `idRoles` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(80) NOT NULL,
  `edit_product` TINYINT NOT NULL,
  `create_product` TINYINT NOT NULL,
  `delete_product` TINYINT NOT NULL,
  `edit_review` TINYINT NOT NULL,
  `create_review` TINYINT NOT NULL,
  `delete_review` TINYINT NOT NULL,
  `dashboard_access` TINYINT NOT NULL,
  `edit_category` TINYINT NOT NULL,
  `create_category` TINYINT NOT NULL,
  `delete_category` TINYINT NOT NULL,
  `edit_user` TINYINT NOT NULL,
  `create_user` TINYINT NOT NULL,
  `delete_user` TINYINT NOT NULL,
  `edit_role` TINYINT NOT NULL,
  `create_role` TINYINT NOT NULL,
  `delete_role` TINYINT NOT NULL,
  PRIMARY KEY (`idRoles`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `p9_uoc`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `p9_uoc`.`Users` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(80) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `gender` ENUM('female', 'male') NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `Rol` INT NOT NULL,
  `date_add` DATE NOT NULL,
  PRIMARY KEY (`id_user`, `Rol`),
  INDEX `fk_Users_Roles1_idx` (`Rol` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  CONSTRAINT `fk_Users_Roles1`
    FOREIGN KEY (`Rol`)
    REFERENCES `p9_uoc`.`Roles` (`idRoles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `p9_uoc`.`Categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `p9_uoc`.`Categories` (
  `idCategory` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  `excerpt` VARCHAR(255) NULL,
  `meta_title` VARCHAR(100) NULL,
  `meta_description` VARCHAR(255) NULL,
  `date_add` DATETIME NOT NULL,
  PRIMARY KEY (`idCategory`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `p9_uoc`.`Products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `p9_uoc`.`Products` (
  `id_product` INT NOT NULL AUTO_INCREMENT,
  `reference` INT NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `description` LONGTEXT NULL,
  `price` FLOAT NOT NULL,
  `imgUrl` VARCHAR(255) NULL,
  `excerpt` VARCHAR(255) NULL,
  `available` TINYINT NOT NULL,
  `meta_title` VARCHAR(100) NULL,
  `meta_description` VARCHAR(255) NULL,
  `date_add` DATE NOT NULL,
  PRIMARY KEY (`id_product`),
  UNIQUE INDEX `idProduct_UNIQUE` (`id_product` ASC),
  UNIQUE INDEX `reference_UNIQUE` (`reference` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `p9_uoc`.`reviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `p9_uoc`.`reviews` (
  `title` VARCHAR(60) NULL,
  `descripction` LONGTEXT NULL,
  `images_url` VARCHAR(100) NULL,
  `rating` INT NOT NULL,
  `User` INT NOT NULL,
  `Product` INT NOT NULL,
  `date_add` DATE NOT NULL,
  PRIMARY KEY (`User`, `Product`),
  INDEX `fk_reviews_Users1_idx` (`User` ASC),
  INDEX `fk_reviews_Products1_idx` (`Product` ASC),
  CONSTRAINT `fk_reviews_Users1`
    FOREIGN KEY (`User`)
    REFERENCES `p9_uoc`.`Users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reviews_Products1`
    FOREIGN KEY (`Product`)
    REFERENCES `p9_uoc`.`Products` (`id_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `p9_uoc`.`Categories_has_Products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `p9_uoc`.`Categories_has_Products` (
  `Category` INT NOT NULL,
  `Product` INT NOT NULL,
  PRIMARY KEY (`Category`, `Product`),
  INDEX `fk_Categories_has_Products_Products1_idx` (`Product` ASC),
  INDEX `fk_Categories_has_Products_Categories1_idx` (`Category` ASC),
  CONSTRAINT `fk_Categories_has_Products_Categories1`
    FOREIGN KEY (`Category`)
    REFERENCES `p9_uoc`.`Categories` (`idCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Categories_has_Products_Products1`
    FOREIGN KEY (`Product`)
    REFERENCES `p9_uoc`.`Products` (`id_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
